### ISSUE TITLE
DeepLSD model is not downloadable

### ISSUE THREAD

**Issue by amughrabi** [cvg/limap#36]
Thank you for the wonderful work you've done. I'm facing an issue after running the following steps. I believe the problem is linked to DeepLSD (https://github.com/cvg/DeepLSD#usage), but as this model is essential to the project, I suggest including it as part of the LIMAP repository (i.e. packages).

**Steps:**
```bash
python runners/hypersim/fitnmerge.py --output_dir outputs/quickstart_fitnmerge
```

**Logs:**
```bash
Computing visual neighbors... (n_neighbors = 100)
[LOG] Start 2D line detection and description (detector = deeplsd, n_images = 98)...
Downloading DeepLSD model...
--2023-07-19 15:07:22--  https://www.polybox.ethz.ch/index.php/s/XVb30sUyuJttFys/download
Resolving www.polybox.ethz.ch (www.polybox.ethz.ch)... 129.132.71.243
Connecting to www.polybox.ethz.ch (www.polybox.ethz.ch)|129.132.71.243|:443... connected.
HTTP request sent, awaiting response... 503 Service Unavailable
2023-07-19 15:07:22 ERROR 503: Service Unavailable.

Traceback (most recent call last):
  File "runners/hypersim/fitnmerge.py", line 41, in <module>
    main()
  File "runners/hypersim/fitnmerge.py", line 38, in main
    run_scene_hypersim(cfg, dataset, cfg["scene_id"], cam_id=cfg["cam_id"])
  File "runners/hypersim/fitnmerge.py", line 14, in run_scene_hypersim
    linetracks = limap.runners.line_fitnmerge(cfg, imagecols, depths)
  File "/home/amughrabi/projects/limap/limap/runners/line_fitnmerge.py", line 98, in line_fitnmerge
    all_2d_segs, _ = _runners.compute_2d_segs(cfg, imagecols, compute_descinfo=cfg["line2d"]["compute_descinfo"])
  File "/home/amughrabi/projects/limap/limap/runners/functions.py", line 135, in compute_2d_segs
    detector = limap.line2d.get_detector(cfg["line2d"]["detector"], max_num_2d_segs=cfg["line2d"]["max_num_2d_segs"], do_merge_lines=cfg["line2d"]["do_merge_lines"], visualize=cfg["line2d"]["visualize"], weight_path=weight_path)
  File "/home/amughrabi/projects/limap/limap/line2d/register_detector.py", line 25, in get_detector
    return DeepLSDDetector(options)
  File "/home/amughrabi/projects/limap/limap/line2d/DeepLSD/deeplsd.py", line 26, in __init__
    self.download_model(ckpt)
  File "/home/amughrabi/projects/limap/limap/line2d/DeepLSD/deeplsd.py", line 39, in download_model
    subprocess.run(cmd, check=True)
  File "/home/amughrabi/anaconda3/envs/limap/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['wget', 'https://www.polybox.ethz.ch/index.php/s/XVb30sUyuJttFys/download', '-O', '/home/amughrabi/.limap/models/line2d/DeepLSD/deeplsd_md.tar']' returned non-zero exit status 8.

```

**Comment by B1ueber2y** [comment]
Hi. Does it work now? It seems to be a temporary network connection problem. Thanks!
