### ISSUE TITLE
Quickstart example failing at verify_matches with docker

### ISSUE THREAD

**Issue by kunalchelani** [cvg/limap#66]
Running `python runners/hypersim/fitnmerge.py --output_dir outputs/quickstart_fitnmerge` in the docker container fails.

Here is the error trace:

Traceback (most recent call last):
  File "/limap/runners/hypersim/fitnmerge.py", line 41, in <module>
    main()
  File "/limap/runners/hypersim/fitnmerge.py", line 38, in main
    run_scene_hypersim(cfg, dataset, cfg["scene_id"], cam_id=cfg["cam_id"])
  File "/limap/runners/hypersim/fitnmerge.py", line 14, in run_scene_hypersim
    linetracks = limap.runners.line_fitnmerge(cfg, imagecols, depths)
  File "/limap/limap/runners/line_fitnmerge.py", line 106, in line_fitnmerge
    _, neighbors, ranges = _runners.compute_sfminfos(cfg, imagecols)
  File "/limap/limap/runners/functions.py", line 126, in compute_sfminfos
    _psfm.run_colmap_sfm_with_known_poses(cfg["sfm"], imagecols, output_path=colmap_output_path, skip_exists=cfg["skip_exists"])
  File "/limap/limap/pointsfm/colmap_sfm.py", line 195, in run_colmap_sfm_with_known_poses
    run_hloc_matches(cfg["hloc"], image_path, Path(db_path), keypoints=keypoints_in_order, neighbors=neighbors, imagecols=imagecols_tmp)
  File "/limap/limap/pointsfm/colmap_sfm.py", line 110, in run_hloc_matches
    triangulation.estimation_and_geometric_verification(db_path, sfm_pairs)
  File "/limap/third-party/Hierarchical-Localization/hloc/triangulation.py", line 109, in estimation_and_geometric_verification
    pycolmap.verify_matches(
TypeError: verify_matches(): incompatible function arguments. The following argument types are supported:
    1. (database_path: object, pairs_path: object, options: pycolmap.TwoViewGeometryOptions = <pycolmap.TwoViewGeometryOptions object at 0x7f81852bdcb0>) -> None

Invoked with: PosixPath('outputs/quickstart_fitnmerge/colmap_outputs/db.db'), PosixPath('outputs/quickstart_fitnmerge/colmap_outputs/hloc_outputs/pairs-exhaustive.txt'); kwargs: max_num_trials=20000, min_inlier_ratio=0.1

There seems to be a mismatch between the argument types expected by pycolmap and those supplied by the hloc triangulation code. Could this possibly result from the recently made changes in hloc and pycolmap? 

Any help is appreciated! Thanks!

**Comment by kunalchelani** [comment]
Downgrading to pycolmap 0.3 gets rid of the issue.
Closing as this is anyway not an issue with limap but hloc-pycolmap compatibility.
